### ISSUE TITLE
重启之后再打开aria2的下载器显示未连接

### ISSUE THREAD

**Issue by yaphets11** [sxueck/Aria2-AutoInstall#1]

**Comment by sxueck** [comment]
能告诉我你的
%appdata%\Microsoft\Windows\Start Menu\Programs\Startup
目录下有什么文件吗

**Comment by Nover2** [comment]
> 能告诉我你的
> %appdata%\Microsoft\Windows\Start Menu\Programs\Startup
> 目录下有什么文件吗

![image](https://user-images.githubusercontent.com/46912250/52997814-8edd1580-345c-11e9-9501-58863b9e4e1c.png)

我也遇到这个问题，文件如图

**Comment by sxueck** [comment]
这个是我之前的版本(目前已经回滚了) 你可以用git更新最新的版本重新安装

**Comment by sxueck** [comment]
请重新下载完成安装即可
